if [[ $ZSH_THEME != "powerlevel10k/powerlevel10k" ]] ; then
    return
fi

# prompt settings
POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs os_icon)
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="╭─"
POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX="├─"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="╰─"

# context (username and host)
POWERLEVEL9K_CONTEXT_TEMPLATE="%n@%m"
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="0"
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="7"

# dir
POWERLEVEL9K_DIR_SHOW_WRITABLE=true
POWERLEVEL9K_DIR_HOME_FOREGROUND="0"
POWERLEVEL9K_DIR_HOME_BACKGROUND="4"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="0"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="4"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="0"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="2"
POWERLEVEL9K_DIR_ETC_FOREGROUND="0"
POWERLEVEL9K_DIR_ETC_BACKGROUND="6"
POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND="0"
POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND="3"
POWERLEVEL9K_DIR_NOT_WRITABLE_VISUAL_IDENTIFIER_COLOR="9"

# vcs
POWERLEVEL9K_HIDE_BRANCH_ICON=false
POWERLEVEL9K_SHOW_CHANGESET=true
POWERLEVEL9K_CHANGESET_HASH_LENGTH=7
POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY=true
POWERLEVEL9K_VCS_HIDE_TAGS=false
POWERLEVEL9K_VCS_ACTIONFORMAT_FOREGROUND="9"

# status
POWERLEVEL9K_STATUS_OK_FOREGROUND="0"
POWERLEVEL9K_STATUS_OK_BACKGROUND="2"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="11"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="9"

# background jobs
POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true
POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE_ALWAYS=true
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND="0"
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND="3"

# os icon
POWERLEVEL9K_OS_ICON_FOREGROUND="0"
POWERLEVEL9K_OS_ICON_BACKGROUND="4"

# vim:ft=sh:sts=4:ts=4:sw=4:expandtab
