name:                xmonad-client
version:             0.1.0.0
license:             BSD3
author:              "Kelvin Zhao"
maintainer:          "me@gnux.cn"

dependencies:
- base >= 4.7 && < 5
- X11

executables:
  xmonad-client:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies: []
